ALTER TABLE page
  ADD PRIMARY KEY (id);

ALTER TABLE page ALTER COLUMN is_redirect DROP DEFAULT;
ALTER TABLE page ALTER is_redirect TYPE bool USING CASE WHEN is_redirect=0 THEN FALSE ELSE TRUE END;
ALTER TABLE page ALTER COLUMN is_redirect SET DEFAULT FALSE;

ALTER TABLE page ALTER COLUMN is_new DROP DEFAULT;
ALTER TABLE page ALTER is_new TYPE bool USING CASE WHEN is_new=0 THEN FALSE ELSE TRUE END;
ALTER TABLE page ALTER COLUMN is_new SET DEFAULT FALSE;

CREATE INDEX page_title ON page (title);
CREATE INDEX page_is_redirect ON page (is_redirect);
